name = "hello_world"
description = ""
version = "0.1.0-dev"

authors = ["Jorge Ascencio"]
maintainers = ["Jorge Ascencio <yorchek@gmail.com>"]
maintainers-logins = ["yorche3"]
licenses = "MIT OR Apache-2.0"
website = ""
tags = []

executables = ["hello_world"]