name = "consapp"
description = ""
version = "0.1.0-dev"

authors = ["Jorge Ascencio"]
maintainers = ["Jorge Ascencio <yorchek@gmail.com>"]
maintainers-logins = ["yorche3"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["consapp"]

[[depends-on]]
gnatcoll = "^26.0.0"
