name = "ms_soap"
description = ""
version = "0.1.0-dev"

authors = ["Jorge Ascencio"]
maintainers = ["Jorge Ascencio <yorchek@gmail.com>"]
maintainers-logins = ["yorche3"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["ms_soap"]

[[depends-on]]
aws = "^24.0.0"

[[depends-on]]
gnatcoll = "^24.0.0"     # Librerías de utilidad (manejo de logs, config, etc.)

[[depends-on]]
xmlada = "^24.0.0"       # Necesaria para procesar los esquemas XML

[[depends-on]]
matreshka_soap = "^21.0.0"

[[depends-on]]
matreshka_league = "^21.0.0"

[[depends-on]]
matreshka_xml = "^21.0.0"
