name = "ms_rest"
description = ""
version = "0.1.0-dev"

authors = ["Jorge Ascencio"]
maintainers = ["Jorge Ascencio <yorchek@gmail.com>"]
maintainers-logins = ["yorche3"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["ms_rest"]

[[depends-on]]
aws = "^24.0.0"

[[depends-on]]
gnatcoll = "^24.0.0"

[[depends-on]]
aunit = "^26.0.0"
