name: "SAST - Glot (ShellCheck)"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scripts/**'
  workflow_dispatch:

permissions:
  security-events: write
  contents: read

jobs:
  shellcheck:
    name: ShellCheck Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6 # Actualizado a v6

      - name: Run ShellCheck
        id: ShellCheck # ID necesario para usar el output
        uses: redhat-plumbers-in-action/differential-shellcheck@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          scan-directory: 'scripts'
          exclude-path: |
            scripts/versions/**/*.sh
          # severity: 'warning' # Opcional: ajusta el nivel de severidad

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.ShellCheck.outputs.sarif }}
          category: "shellcheck-glot"
